/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Hibernate;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.Date;

import org.hibernate.*;
import org.hibernate.cfg.Configuration;

public class Library {
    public static void main(String args[]) throws IOException {
    	System.out.println("Hello World");
//    	have to give path in configure if not default
    	SessionFactory factory = new Configuration().configure().buildSessionFactory();
    	
//    	creating student
//    	Student student=new Student();
//    	student.setCity("delhi");
//    	student.setId(101);
//    	student.setName("Aryan");
//    	System.out.println(student);
    	
//    	Creating Address
    	Address ad =new Address();
    	ad.setStreet("st12");
    	ad.setCity("ldh2");
    	ad.setOpen(true);
    	ad.setAddedDate(new Date());
    	ad.setX(121.12);
    	
    	FileInputStream fs = new FileInputStream("src/main/java/homeIndia.png");
    	byte[] data = new byte[fs.available()];
    	fs.read(data);
    	ad.setImage(data);
    	
    	Session session= factory.openSession();
    	
    	Transaction tx= session.beginTransaction();
//    	session.save(student);
    	session.save(ad);
    	tx.commit();
    	
    	session.close();
    	
//    	connection made and object is returned
    	System.out.println(factory);
    }
}
