/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GradleDependency;

import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.LogManager;

public class Library {
	
	private static final Logger logger = LogManager.getLogger();
	
    public static void main(String args[]) {
    	System.out.println("I am gradle main");
    	logger.info("Hello Logs");
    }
}
